### ISSUE TITLE
Poor performance of MCMC draws in `impacts()`

### ISSUE THREAD

**Issue by dhicks** [r-spatial/spdep#14]
I'm fitting a spatial Durbin model using `lagsarlm()` on what seems to me to be not a terribly large dataset (1044 observations).  `impacts()` takes 45-50 seconds to take 10 MCMC draws, which would be ~42 minutes for 500 draws.  Things are even slower with my actual model, which involves 6 or 7 predictors.  I'm not sure whether this poor performance is just because sometimes MCMC is slow or it indicates some serious problem somewhere.  

MWE:  
```
library(magrittr)
library(sf)
library(spdep)

dataf = readRDS('mwe_data.Rds')

weights_3nn = dataf %>%
    st_centroid() %>%
    st_coordinates() %>%
    knearneigh(k = 3) %>%
    knn2nb() %>%
    nb2listw(style = 'W')

model = lagsarlm(w_use ~ hispanicP, data = dataf, weights_3nn, type = 'Durbin')

# tictoc::tic()
model_impacts = impacts(model, listw = weights_3nn, R = 10)
# tictoc::toc()
```

[Dataset](https://github.com/r-spatial/spdep/files/2055246/mwe_data.Rds.zip)

**Comment by rsbivand** [comment]
Use matrix traces, do not invert the nxn matrix for each value of \rho. I can follow up tomorrow if you can't see the obvious documentation, and I need a reprex.

**Comment by dhicks** [comment]
Thanks for the quick reply.  I'm not 100% confident I understand, in part because I'm not sure I understand exactly how the MCMC version of `impacts()` works.  But it seems like I can construct the matrix traces like this:  
```
traces = trW(as(weights_3nn, 'CsparseMatrix'))
```
and then use them in `impacts()` as
```
model_impacts = impacts(model, tr = traces, R = 500)
```

I'm not sure how to set the arguments in `trW()` correctly.  But this `impacts()` call takes less than a second.  So if the defaults for `trW()` are likely to work, I'm probably good and you can close this issue.  Thanks again!

**Comment by rsbivand** [comment]
Essentially everything you need to know is in `?impacts` or its references. For GM and ML model fits with lagged responses (including panel models from **splm**), the inferences on impacts are by MC (not MCMC) either inverting the (I - \rhoW) for each drawn value of \rho, or by traces as shown for example by LeSage & Pace (2009). The samples for inference are drawn from a multivariate normal distribution using the coefficients and their variance-covariance matrix. The output is stored in `mcmc` objects for convenience. If the model was fitted using Bayesian MCMC, the samples are already drawn.

The arguments to `trW()` are described in `?trW`; the default finds the first `m` power traces by sparse matrix multiplication rather than by MC simulation. If in doubt, refer to LeSage & Pace (2009). If in doubt, change `m` and maybe `type` and see if it makes any difference.
