### ISSUE TITLE
Relationship (and conversion) between nb and sgbp objects

### ISSUE THREAD

**Issue by agila5** [r-spatial/spdep#145]
Dear all, 

I created this issue since I have a (possibly trivial) question regarding the relationship between [`sgbp`](https://r-spatial.org/book/07-Introsf.html#binary-predicates) and [`nb`](https://r-spatial.org/book/14-Areal.html#representing-proximity-in-spdep) objects. According to the descriptions in the SDSR book, it appears to me that these two objects represent, more or less, the same concept: they summarise a (binary) relationship between spatial objects using an adjacency list where `x[[i]]` is a vector of n>=0 indices that correspond to the indices of neighbours (according to some definition of neighbourhood). 

Moreover, I noticed that the two classes have internally very similar structures: 
``` r
library(spdep)
#> Loading required package: spData
#> Loading required package: sf
#> Linking to GEOS 3.11.2, GDAL 3.7.2, PROJ 9.3.0; sf_use_s2() is TRUE
grid <- st_make_grid(cellsize = c(1, 1), offset = c(0, 0), n = c(2, 2))
sgbp <- st_intersects(grid)
nb <- poly2nb(grid)

sgbp |> unclass() |> str()
#> List of 4
#>  $ : int [1:4] 1 2 3 4
#>  $ : int [1:4] 1 2 3 4
#>  $ : int [1:4] 1 2 3 4
#>  $ : int [1:4] 1 2 3 4
#>  - attr(*, "predicate")= chr "intersects"
#>  - attr(*, "region.id")= chr [1:4] "1" "2" "3" "4"
#>  - attr(*, "remove_self")= logi FALSE
#>  - attr(*, "retain_unique")= logi FALSE
#>  - attr(*, "ncol")= int 4
nb |> unclass() |> str()
#> List of 4
#>  $ : int [1:3] 2 3 4
#>  $ : int [1:3] 1 3 4
#>  $ : int [1:3] 1 2 4
#>  $ : int [1:3] 1 2 3
#>  - attr(*, "region.id")= chr [1:4] "1" "2" "3" "4"
#>  - attr(*, "call")= language poly2nb(pl = grid)
#>  - attr(*, "type")= chr "queen"
#>  - attr(*, "sym")= logi TRUE
```

<sup>Created on 2024-03-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Maybe I'm missing something obvious, but I was wondering: is it possible to convert `sgbp` to `nb` and vice versa? Can I simply (inter)change the classes of the two objects? I'm asking this question since, IMO, it might be really convenient being able to define neighbours among geometries using any of the spatial predicates listed [here](https://r-spatial.org/book/03-Geometries.html#sec-de9im).

**Comment by edzer** [comment]
Yes, there should of course be an easy conversion option. The way I see it, `sgbp` comes out of binary predicates like `st_intersects`, and only corresponds to `nb` when this was called with a single argument, that is when you know that the (full logical) matrix is square. If called with two objects `x` and `y` with a different number of geometries, `sgbp` represents a non-square matrix and needs to keep track of the number of columns (for `nb` this equals its length).

**Comment by rsbivand** [comment]
No easy conversion options should be made available, since while the objects look similat, they are used for different purposes and `nb` objects must fulfill many constraints. One, the underlying matrix must be square, two, the principal diagonal must be zero (no self-neighbours), three, the row-column indices must relate to feature FIDs (little used nowadays, but the cause of a published error in the paper on Empirical Bayes Moran's `I`some 20 years ago). 

There are further constraints later (identify no-neighbour observations, identify disjunct sub-graphs) which matter for tests and model-fitting. Testing and model-fitting are the (only) goals for `nb` objects.

So for example `spdep::poly2nb` takes a lot of care with snapping of polygon boundary points that should be considered "close enough" to be identical, so only uses predicates on envelopes to determine candidate neighbours before finally snapping.

So if you simply interchange the objects, many tests may give results which are misleading (should no-neighbour observations be included in `n`?) and many model-fitting functions will fail (`mgcv::gam` can take an `mrf` spatial smoother using an `nb` object with the observation IDs used to name the `nb` list components).

It may be possible to write coercion functions, but in general it is much more convenient to generate `nb` objects directly - I did look at this when `sgbp` objects came into being. There is no use case for `nb` to `sgbp` coercion that I can think of.

**Comment by rsbivand** [comment]
Further see: https://github.com/r-spatial/sf/issues/715, https://github.com/r-spatial/sf/issues/1492, https://github.com/r-spatial/sf/issues/1750, etc. `spdep` does suggest `Matrix`, so as https://github.com/r-spatial/sf/issues/1750 has a skeletal coercion from `sgbp` to `sparseMatrix`, and  https://github.com/r-spatial/sf/issues/715 has a skeletal `sgbp` to `nb` coercion (but neither with validity checks for spatial neighbour objects), adding something to `spdep` is not impossible, but not a priority. My intuition is that the validity checks would take as much time and memory as creating `nb` objects directly from geometries.

**Comment by agila5** [comment]
Dear @edzer and @rsbivand, thank you very much for your very detailed responses, they're extremely helpful. I must admit that I just started working on these topics, so it will take some time to digest all the information that you mentioned. Anyway, if possible, I would keep this issue open in case I can come up with any meaningful use case regarding the `nb` <-> `sgbp` conversion and, otherwise, close it as soon as possible.
