### ISSUE TITLE
install.packages("spdef") fails because of dependency on sf

### ISSUE THREAD

**Issue by pkoppstein** [r-spatial/spdep#36]
```
$ R
R version 3.6.1 (2019-07-05) -- "Action of the Toes"

> install.packages("spdep")
# 64
also installing the dependency 'sf'
./configure: line 2071: test: too many arguments
./configure: line 2075: test: too many arguments

./configure: line 2078: test: too many arguments
configure: CC: clang
configure: CXX: clang++ -std=gnu++11
checking for gdal-config... no
no
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package 'sf'
* removing '/usr/local/Cellar/r/3.6.1/lib/R/library/sf'
....
```

Platform: Mac OS High Sierra

**Comment by rsbivand** [comment]
Install the OSX binary from CRAN, since you do not know how to install from
source, right? No external software installed. I'm offline, this is not a
sensible issue.

Roger Bivand
Falsensvei 32
5063 Bergen

søn. 3. nov. 2019, 06.48 skrev pkoppstein <notifications@github.com>:

**Comment by pkoppstein** [comment]
@rsbivand - Thanks for your response, but I do not fully understand it.

The extract that I included showed an attempt to install spdef using CRAN.  Pretty much the same thing happens if I try installing sf directly.  I've also tried a different CRAN source, e.g.:
```
> install.packages("sf")
# 66
...
./configure: line 2071: test: too many arguments
./configure: line 2075: test: too many arguments
./configure: line 2078: test: too many arguments
configure: CC: clang
configure: CXX: clang++ -std=gnu++11
checking for gdal-config... no
no
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package 'sf'
* removing '/usr/local/Cellar/r/3.6.1/lib/R/library/sf'
```

I wouldn't mind trying to install sf in some other way but would need some guidance.

Thanks again.

**Comment by rsbivand** [comment]
Please read the help page for `install.packages()`, on your own installation, or at https://www.rdocumentation.org/packages/utils/versions/3.6.1/topics/install.packages. Look at the `type=` argument. On Windows R installs, this is `"win.binary"`, and for you should be `"binary"` or one of the OSX-specific variants. If your `getOption("install.packages.compile.from.source")` is not `"binary"`, the function may try to install from source packages, putting the onus for understanding how to install external dependencies on you alone. If this is OK for you, read more on the **sf** repo and on https://cran.r-project.org/package=sf to install the system requirements. If you knew how to do that, you would not have raised this issue on the wrong repo - your problem is in installing **sf** from source when system requirements are missing. Install **sf** first as binary, then **spdep** as binary (with its other dependencies). This is **not** an issue. Post on R-sig-geo or R-sig-mac if you need help installling packages on OSX.
