### ISSUE TITLE
p-values of direct and indirect impacts

### ISSUE THREAD

**Issue by Reale3** [r-spatial/spdep#42]
Hello,
I am trying to get, unsuccessfully, p-values of direct and indirect impacts of a SARMA model.
I can see the direct, indirect, and total impacts by print(obj) or print.summary.lagImpact(obj) but without p-values. 
The code goes as:
#library(spdep)
#library(spatialreg)
#ab.sarma<-sacsarlm(output~X1+X2,data = mydata,listw = W,zero.policy = TRUE)
#obj<-impacts(ab.sarma,listw = W)
#spatialreg::print.summary.lagImpact(obj, zstats=TRUE)

zstats option not giving any output. 
Perhaps, I am missing something small; any help in the direction will help.

Thanks,

**Comment by rsbivand** [comment]
Not this repo, should have been **spatialreg** if it was a bug. For user problems use R-sig-geo, not repo issues. Please read `?spatialreg::impacts` and its examples (also here: https://r-spatial.github.io/spatialreg/reference/impacts.html). Note that `R=` is the number of MC samples to take for inference. If you use `listw=` rather than `tr=`, you invert an nxn matrix for each draw of \rho. Use `trW()` to create the required traces.

**Comment by Reale3** [comment]
Ok, thank you. I will signup and switch to R-sig-geo. After trying your quick tip on using traces first.
