### ISSUE TITLE
nbcosts- no neighbour nodes

### ISSUE THREAD

**Issue by Rosert2019** [r-spatial/spdep#56]
I'm running skater cluster algorithm with my own dataset colled "territories" . bellow different steps:

1.territoriesNb <- poly2nb(territories) summary(territoriesNb), I get

Neighbour list object:
Number of regions: 37 
Number of nonzero links: 134 
Percentage nonzero weights: 9.788167 
Average number of links: 3.621622 
2 regions with no links:
73 100
Link number distribution:

 0  1  2  3  4  5  6  7 11 
 2  2  4 13  7  4  2  2  1 
2 least connected regions:
64 87 with 1 link
1 most connected region:
98 with 11 links

2. when i run: lcosts <- nbcosts(territoriesNb, territoriesSt), I have got this error:

Error in nbcosts(territoriesNb, territoriesSt) : nbcosts: no-neighbour nodes.

MAY SOME SOME HELP TO REMOVE NO-NEIGHBOUR FROM MY SP SPATIALPOLYGOMDATAFRME ?

**Comment by rsbivand** [comment]
There may be several reasons for `poly2nb()` yielding no-neighbours. The obvious one is that the dataset includes real non-contiguous polygons, such as islands. With your smallish data set, you could use `edit.nb()` (not in RStudio) to add links corresponding say to ferries. If the non-contiguities are caused by problems with the input polygons (for example, that the non-contiguities are caused by an intervening river channel, or by faulty input polygons), the `snap=` argument can be used to address the problem. This works best for planar geometries, because the snap distance is Euclidean.
