### ISSUE TITLE
nb should be a list subclass

### ISSUE THREAD

**Issue by JosiahParry** [r-spatial/spdep#59]
nb objects are list objects. However, in creation, they lose their list class due to setting of attributes. This means that any functions that would normally work on a list do not work on an nb class without manually adding the list class ur `unclass()`-ing the `nb` object. The latter approach is unwanted because there are no functions for recasting a list to nb. 

For example in `poly2nb()` https://github.com/r-spatial/spdep/blob/be5d2ad211ae84b3950811e25050eb2f6d5a9132/R/poly2nb.R#L167 should be changed to `class(ans) <- c("nb", "list")`.

**Comment by JosiahParry** [comment]
Further, I think it would be helpful if there was a single construction function that is used to construct nb list objects for all of the various `*2nb()` functions to ease internal consistency

**Comment by edzer** [comment]
> should be changed to class(ans) <- c("nb", "list").

No, that is not needed. S3 classed lists are still lists; you can check this using `is.list()` on a `nb` object. Some of the methods get overridden, you can check which ones with `methods(class = "nb")`, remaining methods fall back to the list (or default) method. Maybe read Ch 3 of https://adv-r.hadley.nz/vectors-chap.html ?

**Comment by edzer** [comment]
Here you go:
```r
> columbus <- st_read(system.file("shapes/columbus.shp", package="spData")[1], quiet=TRUE)
> nb = poly2nb(columbus)
> length(nb)
[1] 49
> dim(columbus)
[1] 49 21
> columbus$nb = nb
```
Your problem is with `tidyverse`, not with R or this package.

**Comment by JosiahParry** [comment]
All good. Built a wrapper around spdep today to fit my needs. Thanks!

**Comment by rsbivand** [comment]
@JosiahParry Could you please describe and motivate your needs? We have been here several times before and never found that such tidying actually worked for most users. There are (apart from @edzer 's correct observation that **spdep** is fully R-base compliant) at least two reasons for not doing this. Firstly, I think you get silently stuck when there are no-neighbour observations, and this requires user intervention. Secondly, you miss (I think) the desirability of exposing specification arguments (you use elipsis only) passed to poly2nb(), which has changed radically both 10 years ago (using GEOS STRtree through **rgeos**) and recently (using STRtree through **sf** a bit less efficiently). 

Of course, any PRs are welcome, given that the class structure should be maintained. By the way, `trans_lag = st_lag(med_house_income, nb, wts)` should be `trans_lag = st_lag(by_pub_trans, nb, wts)` to replicate `spatialreg::lmSLX()`. Durbin-handling also benefits from the linear combination of the unlagged and lagged covariates. 

Generally, keeping the `nb` and/or `listw` objects out of the `data.frame` objects simply leads to clarity, as nothing in the `data.frame` object shows which they are (unless you use column names to show the provenance of the objects). 

I have considered going to `"CsparseMatrix"` of `"igraph"` representations, but neither are as flexible. One challenge with included lists is that nothing re-orders the neighbour or weights objects if rows are chosen from the `data.frame`, which is avoided if the objects are separate.

**Comment by JosiahParry** [comment]
Thanks for the note on the Durbin model. One is probably best served _not_ writing documentation at midnight 😉 

I think this is an aesthetic and design preference. There are a things that led to this. 

The first is that I want to be able to couple the neighbors, weights, and the original sf object together. I want to keep the weights with the object that is being weighted—if that phrasing makes sense. This requires that list be of the same length as the original data which the `nb` class adheres to—though there's the compatibility issue as noted above—but the `listw` does not (length 3). 

The second thing is that `listw` objects contain both the neighbors *and* the weights. This means that the neighbors are stored twice and essentially makes the `poly2nb()` uneeded except for `nb2listw(poly2nb(x))` since the listw stores the neighbors as well. 

Storing the `listw` outside of the dataframe means that if I want to modify the weights / neighbors I have to do so outside of the pipe. This leads to many intermediate variables and slows down my coding. 

As an aside: I played around with tidygraph & igraph representations as well. I think these are useful for looking at spatial network analysis. But I don't think much needs to be done from the `r-spatial` side of the house to get into those representation.

**Comment by rsbivand** [comment]
Yes, `listw` objects are list-based sparse representations. The neighbour component says which observations are the neighbours of which for the chosen definition (integer), and the weights are the edge weights (numeric), just like a sparse matrix. Initially, they were vectors with two start/end pointer vectors, but after I learned lists in AWK, lists just worked. You can choose to want list vectors to always be the length of those in your data, but that is a very limiting subset of the language - both `"htest"` and `"lm"` are lists without a list class. 

Yes, if you need to drop observations, you'll have to subset them first and recreate the nb and wts from the outset. All the test and model functions look for NAs and offer standard choices, subsetting and if need be rebuilding most kinds of nb and wts objects. One problem has been finding ways to register the geometries to the observations so that they are keyed correctly, which is why ID checking code is present.

**Comment by JosiahParry** [comment]
Roger,

Do you mind expanding on the following portion? I’m not sure I entirely
follow and it seems important!

> One problem has been finding ways to register the geometries to the
observations so that they are keyed correctly, which is why ID checking
code is present.

**Comment by rsbivand** [comment]
Briefly, in writing  the EB Moran's I,I couldn't reproduce the results in the paper. It turned out that in the paper a Mapinfo file contained the geometries and a CSV file the data, and were out of register in the published example. So I introduced ` spChk` arguments to use if the variable being tested was a named vector - so those names were checked against the nb object region.id attributes. Clunky, but a way to double-check.
