### ISSUE TITLE
zero.policy = TRUE doesn't appear to make a difference

### ISSUE THREAD

**Issue by BriceonWiley** [r-spatial/spdep#61]
Hi, I'm currently using spdep to try and test for spatial dependence within my data, however, I can't get the list of weights because nb2listw is telling me to have 'zero.policy=TRUE' when I already have it included in the function call.
```
> nb <- poly2nb(houston)
> nb2listw(neighbours = nb,  zero.policy = TRUE)
Error in print.listw(x) : 
  regions with no neighbours found, use zero.policy=TRUE
```
Where the houston object is the zip code .shp shapefile read in from [here](https://cohgis-mycity.opendata.arcgis.com/datasets/zip-codes-3/explore?location=29.782204%2C-95.361901%2C10.74).

Are there any suggestions as to why this might be happening?

**Comment by BriceonWiley** [comment]
Thank you so much for following up about this. I was also concerned about the no neighbor observations and if that was a permanence or if something like the `snap=` argument could help. I also was unaware of the `set.ZeroPolicyOption(TRUE)` line; that seems to have fixed what my issues were. Nevertheless, I'm going to continue to look into things and make sure I don't need to re-evaluate the geometries and potentially change the tolerance.

**Comment by chetandoddamani** [comment]
Hi Professor @rsbivand 
I am trying to model spatial regression model. However, there are several issues in my file which is restricting to model. Majorly "error due to missing neighbors". That is, I am not able to convert the file from "queen.nb to queen.listw"
I am attaching my code below. Please help me to overcome this error. 

spat.data = readOGR(dsn = ".", layer = "ward")
" 
OGR data source with driver: ESRI Shapefile 
Source: "E:\IIT-Delhi\Research\Spatial analysis\R analysis", layer: "ward"
with 67 features
It has 33 fields
Integer64 fields read as strings:  ward Population total_hous Survey_hou TW_Sample Car_Sample "

nb <- poly2nb(spat.data, snap=1e-5)
"Neighbour list object:
Number of regions: 67 
Number of nonzero links: 330 
Percentage nonzero weights: 7.351303 
Average number of links: 4.925373 "

nb <- poly2nb(spat.data, snap=1e-5)
nb

nb2listw(neighbours = nb,  zero.policy = TRUE)
print(nb2listw(neighbours = nb,  zero.policy = TRUE),  zero.policy = TRUE)
get.ZeroPolicyOption()
set.ZeroPolicyOption(TRUE)
get.ZeroPolicyOption()
nb2listw(nb)
queen.listw <- nb2listw(queen.nb)
##Error in nb2listw(queen.nb) : object 'queen.nb' not found

nd<- poly2nb(spat.data, queen = TRUE)
summary(nd)

"Neighbour list object:
Number of regions: 67 
Number of nonzero links: 324 
Percentage nonzero weights: 7.217643 
Average number of links: 4.835821 
regions with no links:
41 45
Link number distribution:
0  1  2  3  4  5  6  7  8  9 
2  1  2  8 17 12 13  8  3  1 
1 least connected region:
40 with 1 link
1 most connected region:
37 with 9 links"
I have tried with multiple code to approach. However, i am not able to run the code
I appreciate your time in reviewing my concern.

Thank you

**Comment by rsbivand** [comment]
@chetandoddamani Is this an issue for **spdep** or **spatialreg**? The model fitting fnctions are in **spatialreg**, and all require `zero.policy=TRUE` if there are no-neighbour observations. 

Please provide a working reproducible example.

**Comment by chetandoddamani** [comment]
Hello Professor @rsbivand 
Thank you for your concern. I am trying to create a contiguity matrix and further using spatialreg to understand the spatial dependency on the neighboring wards/zone of polygons. I trying to check for spatial durbin model, spatial durbin error model, and the spatial lag model. I am attaching my code below and after considering _"zero.policy=True"_ I am finding error. The step by step code is below attached here. 

1)
_spat.data = readOGR(dsn = ".", layer = "ward")
summary(spat.data)
queen.nb=poly2nb(spat.data) 
queen.nb=poly2nb(spat.data, zero.policy = TRUE)_
Error in poly2nb(spat.data, zero.policy = TRUE) : 
  unused argument (zero.policy = TRUE)

2) I also tried with above mentioned code as follows. however, i found an error 
_nb <- poly2nb(spat.data, snap=1e-5)
nb
nd <- poly2nb (spat.data,snap=1e-5)
nd
nb2listw(neighbours = nd,  zero.policy = TRUE)
print(nb2listw(neighbours = nb,  zero.policy = TRUE),  zero.policy = TRUE)
get.ZeroPolicyOption()
set.ZeroPolicyOption(TRUE)
get.ZeroPolicyOption()
nb2listw(nd)_

nb2listw(queen.nb,style="ward", zero.policy = FALSE)
##Error in nb2listw(queen.nb, style = "ward", zero.policy = FALSE) :   Style ward invalid

Thank you

**Comment by rsbivand** [comment]
1. There is no `zero.policy=` argument to `poly2nb()`, see `args(polynb)` and `?poly2nb` for valid arguments.
2. There is no valid `style = "ward"`; see `?nb2listw` for valid styles. Please read https://r-spatial.github.io/spdep/articles/nb.html or https://r-spatial.github.io/spdep/articles/nb_sf.html or https://keen-swartz-3146c4.netlify.app/area.html for more information.

If you provide a reproducible example (using a built-in data set or providing your data), it may be possible to provide more help, but now you are not reading clear error messages. Try first reading and understanding the examples shown on the help pages of the functions you are using.
