### ISSUE TITLE
Fatal error on installing spdep

### ISSUE THREAD

**Issue by petra41** [r-spatial/spdep#64]
I am trying to use the Compind package but every time I try to install spData and spdep in RStudio, I get a fatal error.  There is not a message code attached.  I have updated R to version 4.1.2 but that seems to not have helped. Any ideas?

**Comment by rsbivand** [comment]
Please report your operating system. It is very possible that you are using Windows or macOS, and, because a new version of **spdep** was released yesterday, you chose to install the new version from source. If then you are using Windows or macOS, and  do not have the extra tools installed to permit source installs, your attempt will fail. On Windows or macOS, always choose binary installs for packages unless you are sure that you have all of the extra software components needed installed.

It always also helps to install outside RStudio, to remove that layer of extra complication, but in this case the timing suggests that you chose a source install on Windows or macOS, and should have rejected that choice. The CRAN binaries are under preparation and will propagate within a couple of days; it is unlikely that the minor changes in **spdep** matter for your use case.

**Comment by petra41** [comment]
Thank you for your response and the help.  This is on macOS. I can try to still in R directly then if you think that might be the issue?

**Comment by rsbivand** [comment]
Please try:
```
install.packages("Compind", type = "binary")
```
When the CRAN binary for 1.1-12 becomes available, `update.packages()` will install the latest version, but none of the changes affect you.
