### ISSUE TITLE
poly2nb not finding links after June 2021

### ISSUE THREAD

**Issue by matildabrown** [r-spatial/spdep#65]
poly2nb() not detecting non-zero links in SpatialPolygonsDataFrame. 
In versions from June 19 and earlier, finds links, although the number of links is different to that found by the February 2021 version. 

Problem illustrated in poly2nb_version_differences.r attached, using two sets of polygons (p.rds and cells.rds, attached) and run through each version of poly2nb (files named by date of commit, all attached)

[poly2nb_version_differences.zip](https://github.com/r-spatial/spdep/files/7521404/poly2nb_version_differences.zip)

**Comment by rsbivand** [comment]
I'll look a little, but many changes have taken place, see https://cran.r-project.org/web/packages/spdep/news/news.html. Before anything else, which version of GEOS is declared when **sf** is loaded, as this may be related to a bug in GEOS 3.9.0. Further, `snap=` is used once candidates are found by intersecting bounding boxes. 

The dates do not help, please state the CRAN versions of **spdep*, and if possible the CRAN versions of **sf** and other packages used by **spdep**, including their external software dependencies (e.g. `sf_extSoftVersion()`). If you have installed spdep or other software from github, there is no explicit version control (you do always run `sessionInfo()` at the end of you scripts?). 210619 looks like 1.1-7, 210621 looks like 1.1-8, where 1.1-8 and subsequently simplified the STRtree use for spatial indexing. 

What is your use case? Why should the two squares in `p` be seen as touching when they obviously do not? Neither case seems to be spatial data, because there is no declared coordinate reference  system, very odd.

**Comment by rsbivand** [comment]
Adding an argument `odd` and using it in `if (odd || inherits(pl0, "try-error"))` in the latest version: `poly2nb_Nov11_2021(p, snap=5, odd=TRUE)` gives 2 links, and 3036 for `cells`. The case you were using was not intended, but I'll look and see whether I didn't over-simplify.

**Comment by matildabrown** [comment]
Thanks so much for looking at this so quickly, and for the suggested fix! 
Thanks also for the feedback on posting an issue. 

My use case is identifying neighbouring cells; the polygons (cells) are constructed from traced images, where the boundaries are ~3 pixels wide, and thus neighbouring cells (polygons) are ~3 pixels apart. There is no coordinate system because the scale is microscopic, not lat/long, and the points are spatially relative rather than absolute. 

Adding `odd` as suggested works, but generates this warning message - I'm not sure if it's something of concern or if it can be suppressed safely: 

`poly2nb: spatial indexing abandoned,
boundaries could not be coerced to "sfc":`

Thanks again. 
-Matilda

**Comment by rsbivand** [comment]
This case has turned out to be very useful, because implicit in the legacy approach (3062 links, Feb3) was that the snap distance was also used to help find candidates. Candidates are found by intersecting feature bounding boxes. These bounding boxes are rectangles, and behave differently when the objects have edges parallel to the coordinate grid (like p) -  this was the GEOS 3.9.0 regression, but isn't the case here. I'm going to try to go back to what was done before, to buffer the bounding  boxes by `snap=` before intersecting them to find candidates (Feb3), rather than just intersecting the bounding boxes (Mar1-Jun19); from Jun21 the objects themselves were intersected to find the candidates, so if they didn't touch, no candidates were found. I'll let you know when I have a candidate on github.

**Comment by rsbivand** [comment]
@matildabrown Please try `remotes::install_github("r-spatial/spdep")` or download for Windows if that is easier: 
[spdep_1.1-13.zip](https://github.com/r-spatial/spdep/files/7528488/spdep_1.1-13.zip)
I still need to check whether I haven't re-introduced time-consuming extra steps for other cases, but this gets us back to 3062 links for snap=10 for cells.

**Comment by matildabrown** [comment]
Works as expected! I'll test on the rest of the images in my dataset to be sure. 

Installing from `remotes` generates following warnings:
`Warning messages:
1: S3 methods ‘close.processx_connection’, ‘close_named_pipe.unix_named_pipe’, ‘close_named_pipe.windows_named_pipe’, ‘conditionMessage.system_command_error’, ‘conn_is_incomplete.processx_connection’, ‘conn_read_chars.processx_connection’, ‘conn_read_lines.processx_connection’, ‘conn_write.processx_connection’, ‘format.system_command_error’, ‘is_pipe_open.unix_named_pipe’, ‘is_pipe_open.windows_named_pipe’, ‘print.system_command_error’, ‘write_lines_named_pipe.unix_named_pipe’, ‘write_lines_named_pipe.windows_named_pipe’ were declared in NAMESPACE but not found 
2: S3 methods ‘close.processx_connection’, ‘close_named_pipe.unix_named_pipe’, ‘close_named_pipe.windows_named_pipe’, ‘conditionMessage.system_command_error’, ‘conn_is_incomplete.processx_connection’, ‘conn_read_chars.processx_connection’, ‘conn_read_lines.processx_connection’, ‘conn_write.processx_connection’, ‘format.system_command_error’, ‘is_pipe_open.unix_named_pipe’, ‘is_pipe_open.windows_named_pipe’, ‘print.system_command_error’, ‘write_lines_named_pipe.unix_named_pipe’, ‘write_lines_named_pipe.windows_named_pipe’ were declared in NAMESPACE but not found `

From `sessionInfo()` :

`R version 4.1.2 (2021-11-01) 
Platform: x86_64-w64-mingw32/x64 (64-bit) 
Running under: Windows 10 x64 (build 19043)`
