### ISSUE TITLE
Robust Standard Errors in spatial error models

### ISSUE THREAD

**Issue by orlando-sabogal** [r-spatial/spdep#69]
This is probably an issue more related to the documentation. 
I asked [this question on stack overflow](https://stackoverflow.com/questions/70173881/robust-standard-errors-in-spatial-error-models) but I think it is helpful to bring it here. 

I am fitting a Spatial Error Model using the **errorsarlm()** function in the spdep library. The Breusch-Pagan test for spatial models, calculated using the **bptest.sarlm()** function, suggest the presence of heteroskedasticity.

A natural next step would be to get the robust standard error estimates and update the p-values. In the documentation of the **bptest.sarlm()** function says the following:

> lm.target <- lm(error.col$tary ~ error.col$tarX - 1)
if (require(lmtest) && require(sandwich)) {
  print(coeftest(lm.target, vcov=vcovHC(lm.target, type="HC0"), df=Inf))} 

where **error.col** is the spatial error model estimated.

Now, I can easily adapt the code to my problem and get the robust standard errors. Nevertheless, I was wondering:

- What exactly is the “lm.target” component of sarlm objects? I can not find any mention to it in the spdep documentation.
- What exactly are $tary and $tarX? Again, it does not seem to be mentioned on the documentation.
- Why documentation says it is "technically possible to make heteroskedasticity corrections"? Does it mean that proposed approach is not really recommended to overcome issues of heteroskedasticity?

**Comment by rsbivand** [comment]
First, this issue is not for this package https://github.com/r-spatial/spdep/issues/31, but for **spatialreg** https://github.com/r-spatial/spatialreg, please raise it there if you wish. Further, computing on maximum likelihood standard errors makes very little sense, but methods for robust standard errors are more naturally handled by GMM (the **sphet** package) https://github.com/gpiras/sphet. What you are suggesting is to take a position on informed priors in a Bayesian setting, where ML corresponds to uninformative priors. If you want something like this, either go with GMM, or Bayesian informative priors.
