### ISSUE TITLE
d1 and d2 in dnearneigh

### ISSUE THREAD

**Issue by frandadamo** [r-spatial/spdep#80]
Hello everyone,

I’d have a (very basic) clarification to ask, please.

I have to account for spatial autocorrelation in `spatialreg::errorsarlm` models, and I am trying both the `tri2bn` and `dnearneigh `functions. As far as I understood, `tri2bn` is a straightforward function that produces arbitrary diagonal neighbours (likely not a sensible option), while `dnearneigh` allows the creation of a more appropriate neighbour list object by manually setting d1 and d2. Using one or the other function produces significant changes in model outputs, so I want to get this right.

How do I properly set d1 and d2 in `dnearneigh`? For instance, I am working with GeoTIFF raster data at a spatial resolution of 25 km x 25 km (my study area has 281 pixels). After converting these raster data into a data frame, I have lat/long values for each pixel. Given the resolution of my data, I set d1 = 0 and d2 = 25, which seemed a reasonable approach after reading [Bivand and Wond (2018)](https://link.springer.com/article/10.1007/s11749-018-0599-x) and [Dray et al. (2006)](https://www.sciencedirect.com/science/article/pii/S0304380006000925). However, reducing d2 to 24, 23, […], down to until ca. 9 does not change anything in the neighbour list object (i.e., `the number of regions`, `number of nonzero links`, `percentage nonzero weights`, and `average number of links` are exactly the same). Only with ca. d2 ≤ 8 the neighbour list object starts to change. I was therefore thinking to set my d2 as the value that maximises the neighbour list object (i.e., 9 in my case). Is this correct? But still, I do not fully understand the logic behind d1 and d2. Maybe this depends on the type of the coordinate system (i.e., geographic vs. projected)?

Thank you very much,

Francesco

**Comment by rsbivand** [comment]
Always provide fully reproducible examples. Try to use built-in data sets when doing this. Without a working example reproducing your problem, any reply will simply be guesswork.

**Comment by frandadamo** [comment]
Dear Roger,

Many thanks for your reply and my apologies for not appropriately opening an issue.

I looked for appropriate built-in data, but I eventually decided to use a chunk of my data as they best address the question. Hope this is still ok.

Here is the reprex. Adding `longlat=T` allowed me to understand a bit more of the `dnearneigh` function as now distances are measured in km. Setting d2=900 maximises the neighbour list object, and this makes sense as ca. 900km is the maximum distance within the study area (see figure below). However, I do not think that setting d2=900 is correct. I mean, If I run non-autoregressive models, I have spatial autocorrelation up to ca. 250 km. Would it be more appropriate to set d2=250 then? Or d2=900 is the right distance?

Thank you very much again!

```
### reprex issue 80###

#---- library ----
library(tidyverse)
library(spdep)
library(spatialreg)

#---- get the data ----
I80 <- read.csv(url("https://raw.githubusercontent.com/frandadamo/frandadamo/main/Issue_80.csv"))
head(I80)
I80$X <- NULL

#just get lat/long
I80 <- I80 %>% dplyr::select(x,y)

#---- tri2nb (not the best) ----
nb80 <- tri2nb(I80)
# plot(nb80, I80, col="green", pch=20, cex=1)

#---- dnearneigh ----
#1. longlat = F
dne80 <- dnearneigh(as.matrix(I80), 0, 25) #start with d2=25 as each pixel is 25km x 25 km
# plot(dne80, as.matrix(I80), col="green", pch=20, cex=1)

dne80_a <- dnearneigh(as.matrix(I80), 0, 15) #progressively decrease d2: Neighbour list object does not change until ca. d2=9
dne80_b <- dnearneigh(as.matrix(I80), 0, 8)  #d2=8: Neighbour list object is different

#2. longlat = T
dne80_c <- dnearneigh(as.matrix(I80), 0, 900, longlat=T)
#with longlat=T distances are in km (which is more appropriate)
#'d2=900 with longlat=T' is ca. the same as 'd2=25 with longlat=F'
```

**Maximum distance**
![900](https://user-images.githubusercontent.com/97028829/154840139-f6da0909-b81a-49c5-bcb3-7222b967a081.png)

**Comment by rsbivand** [comment]
There is a lot of muddle here. Firstly and most important, the points are in geographical coordinates, so `tri2nb()` should not be used:
```
I80 <- read.csv(url("https://raw.githubusercontent.com/frandadamo/frandadamo/main/Issue_80.csv"))
library(spdep)
I80$X <- NULL
sp_I80 <- I80
coordinates(sp_I80) <- c("x", "y")
slot(sp_I80, "proj4string") <- CRS("EPSG:4326")
is.projected(sp_I80)
sf_I80 <- st_as_sf(I80, coords=c("x", "y"), crs="EPSG:4326")
st_is_longlat(sf_I80)
nb80_sp <- tri2nb(as(sp_I80, "SpatialPoints"))
# Warning message:
# In tri2nb(as(sp_I80, "SpatialPoints")) :
#  tri2nb: coordinates should be planar
nb80_sf <- tri2nb(st_geometry(sf_I80))
# Warning message:
# In tri2nb(st_geometry(sf_I80)) : tri2nb: coordinates should be planar
```
Secondly, at 250km distance, there will be large numbers of neighbours, over-smoothing any spatial process:
```
k1 <- knn2nb(knearneigh(sf_I80, k=1))
md <- range(unlist(nbdists(k1, sf_I80)))
md
[1] 23.47777 37.04614
```
All cells will be linked to at least one other at 38km. 
```
dne80_38km <- dnearneigh(sf_I80, d1=0, d2=38)
n.comp.nb(dne80_38km)$nc
[1] 1
```
in a single graph (with 2.1% non-zero links). This is all that is needed to represent the spatial process, because the theoretical process runs through the inverse of a function of (I - \rho W), (I - \rho W)^{-1}, which is a dense matrix covering the whole graph. 
```
plot(dne80_38km, st_geometry(sf_I80))
```
![image](https://user-images.githubusercontent.com/10198404/154848728-0cff190a-e1a8-412b-8d24-672d15276209.png)
while 41% of all possible links are included for 250km:
```
dne80_250km <- dnearneigh(sf_I80, d1=0, d2=250)
plot(dne80_250km, st_geometry(sf_I80))
```
![image](https://user-images.githubusercontent.com/10198404/154848766-cf904a63-5239-4e4d-9a16-efc35e47596e.png)
Note that because the objects used are specified as being in geographical coordinates, the correct measurements are used. Planar measurements should never be used for geographical coordinates (spherical distances are also used for the k-nearest neighbour object used to find the shortest distance between the points that are furthest apart).

In ecology, it might be possible to use inverse distance weights for a large `d2` value, but this presumes that the researcher knows how the process attenuates, while use of a simple sparse graph does not presuppose that knowledge; in that case `nbdists()` would be used to define weights. Most of this is covered briefly in the function help pages: https://r-spatial.github.io/spdep/ under reference, and in references given therein (the nb2listw() style= question), and in the relevant chapter of https://keen-swartz-3146c4.netlify.app/area.html.

**Comment by frandadamo** [comment]
Dear Roger,
Fantastic, many thanks for this! Very appreciated.
